### ISSUE TITLE
request: ECC hardware acceleration

### ISSUE THREAD

**Issue by arenantonio92** [Bizyroth/Elliptic-Curve-on-ESP32#1]
Hello, 
does the ESP32 platform provide for elliptic curve hardware acceleration? 
If it does, does your code leverage it? 

Thanks for you answer,
Antonio

**Comment by Bizyroth** [comment]
Hello and sorry for the late answer,
In the datasheet of Espressif, it is written that there is an hardware acceleration for ECC ([page 3](https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf)).

I didn't take it in consideration during the developpment and it depends if it is supported by the micro-ECC files (it is not written so i suppose it's no). I add a link to the original git repository of the micro-ECC project, maybe you will have more information there
